replicaCount: 3
image:
  repository: jlarantes/learnpath
  tag: 0.2
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8000
resources: {}

namespace: learnpath
limits:
  memory: "128Mi"
  cpu: "500m"
requests:
  memory: "64Mi"
  cpu: "250m"
ingress:
  enabled: false
  host: learnpath.service.local

rollout:
  enabled: true
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 2m}
        - setWeight: 20
        - pause: {duration: 2m}
        - setWeight: 60
        - pause: {duration: 2m}
        - setWeight: 80
        - pause: {duration: 2m}